### ISSUE TITLE
Name of the repository

### ISSUE THREAD

**Issue by hyviquel** [Pikciochain/PikcioChainSDK#3]
It is usually a good practice too put the name of the project in the name of the repository: Indeed, if someone clone the repository on his machine, he can hardly identify the folder later with a generic name like PythonSDK.

**Comment by jorickMuB** [comment]
You are fully right. We are setting up a next update including a more efficidnt tree model, thus a matching repo / project name.

**Comment by Pikciochain** [comment]
We are working on the new release of PikcioChain SDK, along with the new version of PikcioMe (keep posted on pikcio.me).
The repository name has been updated ;)
